project:
  type: website
  output-dir: docs

website:
  title: "Cancer information seeking among adults in the U.S."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: report.qmd
        text: Report
      - href: data.qmd
        text: About the Data

format:
  html:
    theme: flatly
    toc: true
    toc-depth: 3
    code-fold: true
    fig-width: 8
    fig-height: 5



